version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
        command: sh -c "npm rebuild esbuild && npm run dev"
